music_directory "/data/dlna/music"
playlist_directory "/data/dlna/playlists"
db_file "/data/dlna/database"
state_file "/data/dlna/state"
sticker_file "/data/dlna/sticker.sql"
log_file "/data/dlna/mpd.log"
pid_file "/data/dlna/mpd.pid"

bind_to_address "127.0.0.1"
bind_to_address "/data/dlna/mpd.sock"
port "6600"
zeroconf_enabled "no"
local_permissions "read,add,player,control"

audio_output {
    type "fifo"
    name "Snapcast-DLNA"
    path "/data/dlnafifo"
    format "48000:16:2"
    mixer_type "software"
}
