[supervisord]
nodaemon=true
logfile=/data/dlna/supervisord.log
logfile_maxbytes=0
pidfile=/data/dlna/supervisord.pid

[program:mpd]
command=/usr/bin/mpd --no-daemon /etc/mpd.conf
autostart=true
autorestart=true
startsecs=3
startretries=5
priority=10
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:upmpdcli]
command=/usr/local/bin/snapcast-upmpdcli-entrypoint
autostart=true
autorestart=true
startsecs=5
startretries=5
priority=20
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
