friendlyname = Snapcast-DLNA
avfriendlyname = Snapcast-DLNA
ohproductroom = Snapcast-DLNA
upnpav = 1
openhome = 1
useipv6 = 0
upnpip = 192.168.2.125
upnpport = 49152
plgmicrohttpport = 49149

mpdhost = 127.0.0.1
mpdport = 6600

cachedir = /data/dlna/cache
pidfile = /data/dlna/upmpdcli.pid
logfilename = /data/dlna/upmpdcli.log
