music_directory "/app/data/dlna/library"
playlist_directory "/app/data/dlna/playlists"
db_file "/app/data/dlna/database"
state_file "/app/data/dlna/state"
sticker_file "/app/data/dlna/sticker.sql"
log_file "/app/data/dlna/mpd.log"
pid_file "/app/data/dlna/mpd.pid"

bind_to_address "127.0.0.1"
bind_to_address "/app/data/dlna/mpd.sock"
port "6600"
zeroconf_enabled "no"
local_permissions "read,add,player,control"

audio_output {
    type "fifo"
    name "Snapcast-DLNA"
    path "/app/data/dlnafifo"
    format "48000:16:2"
    mixer_type "software"
}
