friendlyname = Snapcast-DLNA
avfriendlyname = Snapcast-DLNA
ohproductroom = Snapcast-DLNA
upnpav = 1
openhome = 0
ownqueue = 1
avtautoplay = 1
useipv6 = 0
upnpip = 192.168.2.125
upnpport = 49152
plgmicrohttpport = 49149

mpdhost = 127.0.0.1
mpdport = 6600

cachedir = /app/data/dlna/cache
pidfile = /app/data/dlna/upmpdcli.pid
logfilename = /app/data/dlna/upmpdcli.log
loglevel = 3
